eureka:
  build: mrlocksmith-server-eureka
  ports:
  - "8761:8761"
index:
  build: mrlocksmith-index
  links:
  - eureka
register:
  build: mrlocksmith-register
  links:
  - eureka
order:
  build: mrlocksmith-order
  links:
  - eureka
quotation:
  build: mrlocksmith-quotation
  links:
  - eureka  
zuul:
  build: mrlocksmith-server-zuul
  links:
  - eureka
  ports:
  - "8080:8080"
#turbine:
#  build: mrlocksmith-server-turbine
#  links:
#   - eureka
#  ports:
#    - "8989:8989"